// swift-tools-version: 5.9
//
// HandShakerCore — Swift SDK for the HandShaker Rust backend (Phase F).
//
// The native library is shipped as a prebuilt XCFramework whose module
// ("HandShakerFFI", see crates/handshaker-ffi/include/module.modulemap)
// exposes the stable C ABI (handshaker_ffi.h, ABI 1.5.0).
//
// The XCFramework at Artifacts/HandShakerFFI.xcframework is generated by
// the repo build scripts (cargo build + xcodebuild -create-xcframework);
// it must exist before `swift build` resolves this package.

import PackageDescription

let package = Package(
    name: "HandShakerCore",
    platforms: [
        .macOS(.v13),
    ],
    products: [
        .library(name: "HandShakerCore", targets: ["HandShakerCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "HandShakerFFI",
            path: "Artifacts/HandShakerFFI.xcframework"
        ),
        .target(
            name: "HandShakerCore",
            dependencies: ["HandShakerFFI"]
        ),
        .testTarget(
            name: "HandShakerCoreTests",
            dependencies: ["HandShakerCore"]
        ),
    ]
)
