// swift-tools-version: 5.9
//
// HandShakerCore — Swift SDK for the HandShaker Rust backend (Phase F).
//
// The native library is shipped as a prebuilt XCFramework whose module
// ("HandShakerFFI", see crates/handshaker-ffi/include/module.modulemap)
// exposes the stable C ABI (handshaker_ffi.h, ABI 1.5.0).
//
// The XCFramework at Artifacts/HandShakerFFI.xcframework is generated by
// `scripts/build-ffi-macos.sh`, which builds with `LIBUSB_STATIC=1`
// (arm64: Homebrew static libusb; x86_64: vendored static fallback) and
// lipo-merges both architectures. The artifact is therefore **self-
// contained**: it has no libusb dynamic dependency and does not require
// Homebrew at link time (round-2 P1-6) — no `-lusb-1.0`, no
// `-L/opt/homebrew/lib` here. `otool -L` on the staged dylib shows only
// system frameworks; CI's clean-consumer job verifies this.

import PackageDescription

let package = Package(
    name: "HandShakerCore",
    platforms: [
        .macOS(.v13),
    ],
    products: [
        .library(name: "HandShakerCore", targets: ["HandShakerCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "HandShakerFFI",
            path: "Artifacts/HandShakerFFI.xcframework"
        ),
        .target(
            name: "HandShakerCore",
            dependencies: ["HandShakerFFI"]
        ),
        .testTarget(
            name: "HandShakerCoreTests",
            dependencies: ["HandShakerCore"],
            resources: [
                .copy("Fixtures"),
            ]
        ),
    ]
)
