// swift-tools-version: 5.9
//
// HandShakerCore — Swift SDK for the HandShaker Rust backend (Phase F).
//
// The native library is shipped as a prebuilt XCFramework whose module
// ("HandShakerFFI", see crates/handshaker-ffi/include/module.modulemap)
// exposes the stable C ABI (handshaker_ffi.h, ABI 1.5.0).
//
// The XCFramework at Artifacts/HandShakerFFI.xcframework is generated by
// the repo build scripts (cargo build + xcodebuild -create-xcframework);
// it must exist before `swift build` resolves this package.
//
// Linking libusb: `rusb` links the system libusb dynamically when
// pkg-config finds it at build time (GitHub Actions macOS runners have
// Homebrew libusb), so the static libhandshaker_ffi.a carries undefined
// `_libusb_*` references that must be resolved when linking the Swift
// product. On local machines the same archive is self-contained (the
// libusb1-sys fallback bundles libusb statically), so `-lusb-1.0` is a
// no-op there — the flags are safe on both. Homebrew libusb lives in
// /opt/homebrew/lib on arm64 runners (and /usr/local/lib on Intel).

import PackageDescription

let package = Package(
    name: "HandShakerCore",
    platforms: [
        .macOS(.v13),
    ],
    products: [
        .library(name: "HandShakerCore", targets: ["HandShakerCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "HandShakerFFI",
            path: "Artifacts/HandShakerFFI.xcframework"
        ),
        .target(
            name: "HandShakerCore",
            dependencies: ["HandShakerFFI"],
            linkerSettings: [
                .linkedLibrary("usb-1.0"),
                .unsafeFlags(["-L/opt/homebrew/lib"]),
            ]
        ),
        .testTarget(
            name: "HandShakerCoreTests",
            dependencies: ["HandShakerCore"]
        ),
    ]
)
